import type { Metadata } from "next"
import Link from "next/link"
import { notFound } from "next/navigation"
import { isValidLocale, type SupportedLocale } from "@/content/config"

export async function generateMetadata({ params }: { params: { lang: string } }): Promise<Metadata> { const es = params.lang === "es"; return { title: es ? "Clases de Inglés en Loja para Niños, Jóvenes y Adultos" : "English Classes in Loja for Children, Young People, and Adults", description: es ? "Clases y cursos de inglés en Loja con teatro, música y conversación para niños, jóvenes y adultos." : "English classes and courses in Loja using theatre, music, and conversation for children, young people, and adults." } }

export default function EnglishClassesLanding({ params }: { params: { lang: string } }) {
  if (!isValidLocale(params.lang)) notFound()
  const es = params.lang === "es"; const lang = params.lang as SupportedLocale
  const groups = es ? [["Niños", "Aprender jugando con canciones, historias, movimiento y vocabulario útil."], ["Jóvenes", "Practicar comunicación, espontaneidad y confianza a través de escenas y proyectos."], ["Adultos", "Usar el inglés con más seguridad en conversaciones, situaciones reales y actividades creativas."]] : [["Children", "Learn through songs, stories, movement, and useful vocabulary."], ["Young people", "Build communication, spontaneity, and confidence through scenes and projects."], ["Adults", "Use English with more confidence in conversations, real situations, and creative activities."]]
  return <main className="mx-auto max-w-5xl px-6 py-24 lg:px-8"><p className="text-xs uppercase tracking-[0.2em] text-deep-red">Playhouse · Loja, Ecuador</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-tight md:text-7xl">{es ? "Clases de inglés para aprender comunicando, creando y actuando" : "English classes for communicating, creating, and performing"}</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-foreground/70">{es ? "Cursos de inglés para niños, jóvenes y adultos con una metodología activa, artística y humana." : "English courses for children, young people, and adults through an active, artistic, and human methodology."}</p><div className="mt-10 flex flex-wrap gap-4"><a className="rounded-full bg-deep-red px-6 py-3 font-semibold text-white" href="https://wa.me/593939576825">{es ? "Consultar disponibilidad" : "Ask about availability"}</a><Link className="rounded-full border border-foreground/20 px-6 py-3 font-semibold" href={`/${lang}/#faq`}>{es ? "Preguntas frecuentes" : "Frequently asked questions"}</Link></div><section className="mt-24 grid gap-5 md:grid-cols-3">{groups.map(([title, text]) => <div key={title} className="rounded-2xl border border-foreground/10 p-6"><h2 className="text-2xl font-semibold">{title}</h2><p className="mt-4 leading-7 text-foreground/70">{text}</p></div>)}</section><section className="mt-24 max-w-3xl"><h2 className="text-3xl font-semibold">{es ? "Inglés que se usa, no solo se estudia" : "English that is used, not only studied"}</h2><p className="mt-5 leading-8 text-foreground/75">{es ? "El teatro y la música ayudan a crear situaciones de escucha, expresión y colaboración. Cada grupo puede trabajar objetivos distintos según su edad, nivel y contexto." : "Theatre and music create situations for listening, expression, and collaboration. Each group can work toward different goals based on age, level, and context."}</p></section></main>
}
